let inventory=JSON.parse(localStorage.getItem('lumeraInventory')||'null')||DEFAULT_PRODUCTS;
const params=new URLSearchParams(location.search);const category=params.get('cat')||'rings';
const names={rings:'Rings',necklaces:'Necklaces',bracelets:'Bracelets'};
const desc={rings:'Six refined ring styles, from solitaires to signets.',necklaces:'Pendant, chain and pearl necklace styles in one dedicated collection.',bracelets:'Cuffs, tennis bracelets and chain styles, shown only while available.'};
let active='All',modalId=null;
document.title=`Luméra | ${names[category]||'Collection'}`;document.querySelector('#categoryTitle').textContent=names[category]||'Collection';document.querySelector('#categoryEyebrow').textContent=`${(names[category]||'Collection').toUpperCase()} COLLECTION`;document.querySelector('#categoryDesc').textContent=desc[category]||'Explore all currently available pieces.';
function save(){localStorage.setItem('lumeraInventory',JSON.stringify(inventory))}
function money(v){return '$'+v.toLocaleString()}
function available(){return inventory.filter(p=>p.collection===category&&p.stock>0)}
function sold(){return inventory.filter(p=>p.collection===category&&p.stock<=0)}
function drawTabs(){const subs=['All',...new Set(inventory.filter(p=>p.collection===category).map(p=>p.sub))];document.querySelector('#tabs').innerHTML=subs.map(s=>`<button class="${s===active?'active':''}" data-s="${s}">${s}</button>`).join('');document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{active=b.dataset.s;drawTabs();draw()})}
function draw(){const all=available(),list=all.filter(p=>active==='All'||p.sub===active);document.querySelector('#styleCount').textContent=all.length;document.querySelector('#grid').innerHTML=list.length?list.map(p=>`<article class="card"><div class="card-img"><img src="${p.image}" alt="${p.name}"><span class="stock">${p.stock} in stock</span></div><div class="card-body"><div class="meta"><span>${p.sub}</span><span>${money(p.price)}</span></div><h3>${p.name}</h3><p class="desc">${p.desc}</p><button class="view" data-id="${p.id}">View Details</button></div></article>`).join(''):'<p>No in-stock products in this selection.</p>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openProduct(b.dataset.id));document.querySelector('#soldNote').hidden=sold().length===0}
function openProduct(id){const p=inventory.find(x=>x.id===id);if(!p||p.stock<=0)return;modalId=id;document.querySelector('#mImg').src=p.image;document.querySelector('#mImg').alt=p.name;document.querySelector('#mType').textContent=`${names[p.collection]} · ${p.sub}`;document.querySelector('#mName').textContent=p.name;document.querySelector('#mDesc').textContent=p.desc;document.querySelector('#mPrice').textContent=money(p.price);document.querySelector('#mStock').textContent=`${p.stock} pieces`;const q=document.querySelector('#mQty');q.value=1;q.max=p.stock;document.querySelector('#mMsg').textContent='';document.querySelector('#modal').classList.add('open')}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>document.querySelector('#modal').classList.remove('open'));
document.querySelector('#buyBtn').onclick=()=>{const p=inventory.find(x=>x.id===modalId),q=Math.floor(Number(document.querySelector('#mQty').value)),msg=document.querySelector('#mMsg');if(!Number.isFinite(q)||q<1){msg.textContent='Enter a valid quantity.';return}if(q>p.stock){msg.textContent=`Only ${p.stock} pieces are available.`;return}p.stock-=q;save();if(p.stock===0){document.querySelector('#modal').classList.remove('open')}else{document.querySelector('#mStock').textContent=`${p.stock} pieces`;document.querySelector('#mQty').max=p.stock;msg.textContent=`Purchased ${q}. Stock updated.`}draw()};
drawTabs();draw();